/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import static Views.UpdateTable.ps;
import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Gaara
 */
public class ThongKe extends javax.swing.JFrame {
    
    public static String PM = "D:\\phieumuon.txt";
//    public JTextArea getTa() {
//        return taBaoCao;
//    }
    public JButton inbc() {
        return jButton2;
    }
//    public static Connection con = Connect.getConnect();
    
    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
       initComponents();
       
//    UpdateTable.LoadDataPM(PM, tbPhieuQuaHan);
    try {
        String sachFilePath = "D:\\sach.txt";
         String khachHangFilePath = "D:\\khachhang.txt";
        String phieuMuonFilePath = "D:\\phieumuon.txt";
         List<String> lines = getLinesWithNonZeroLastElement(PM);
         UpdateTable.LoadDataPM(lines, tbPhieuQuaHan);
        int sum = readFileAndGetColumnSum(sachFilePath, 6);
         int khachHangSum = countTotalLines(khachHangFilePath);
        int phieuMuonSum = countTotalLines(phieuMuonFilePath);
         int phieuQuaHanSum = countLinesWithNonZeroLastElement(phieuMuonFilePath);
         
        this.lbTongSach.setText("Tổng số sách là: " + sum);
         this.lbTongKhach.setText("Tổng số khách hàng: " + khachHangSum);
        this.lbTongPhieu.setText("Tổng số phiếu mượn: " + phieuMuonSum);
         this.lbTongPhieuQuaHan.setText("Tổng số phiếu quá hạn là: " + phieuQuaHanSum);
    } catch (Exception e) {
        e.printStackTrace();
    }
       
    }
   private List<String> getLinesWithNonZeroLastElement(String filePath) throws Exception {
    BufferedReader br = new BufferedReader(new FileReader(filePath));
    List<String> lines = new ArrayList<>();
    String line;
    while ((line = br.readLine()) != null) {
        String[] data = line.split(",");
        if (data.length > 0) {
            String lastElement = data[data.length - 1].trim();
            if (lastElement.equals("0")) {
                lines.add(line);
            }
        }
    }
    br.close();
    return lines;
}
 private int countLinesWithNonZeroLastElement(String filePath) throws Exception {
    BufferedReader br = new BufferedReader(new FileReader(filePath));
    int count = 0;
    String line;
    while ((line = br.readLine()) != null) {
        String[] data = line.split(",");
        if (data.length > 0) {
            String lastElement = data[data.length - 1].trim();
            if (!lastElement.equals("0")) {
                count++;
            }
        }
    }
    br.close();
    return count;
}
   private int readFileAndGetColumnSum(String filePath, int columnIndex) throws Exception {
    BufferedReader br = new BufferedReader(new FileReader(filePath));
    int sum = 0;
    String line;
    while ((line = br.readLine()) != null) {
        String[] data = line.split(",");
        if (data.length >= columnIndex) {
            int value = Integer.parseInt(data[columnIndex - 1].trim());
            sum += value;
        }
    }
    br.close();
    return sum;
}
   private int countTotalLines(String filePath) throws Exception {
    BufferedReader br = new BufferedReader(new FileReader(filePath));
    int totalLines = 0;
    while (br.readLine() != null) {
        totalLines++;
    }
    br.close();
    return totalLines;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhieuQuaHan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbTongSach = new javax.swing.JLabel();
        lbTongPhieu = new javax.swing.JLabel();
        lbTongKhach = new javax.swing.JLabel();
        lbTongPhieuQuaHan = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Thống kê");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Danh sách phiếu mượn quá hạn");

        tbPhieuQuaHan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbPhieuQuaHan);

        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbTongSach.setText("?");

        lbTongPhieu.setText("?");

        lbTongKhach.setText("?");

        jButton2.setText("In báo cáo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbTongPhieuQuaHan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbTongSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbTongKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbTongPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))
                                .addGap(170, 170, 170))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(213, 213, 213)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTongKhach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTongSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTongPhieu)
                        .addGap(28, 28, 28)
                        .addComponent(lbTongPhieuQuaHan)))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        test t = new test();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try {
        JFileChooser jfc = new JFileChooser("Save File");
        if (jfc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            StringBuilder content = new StringBuilder();
            
            // Lấy dữ liệu từ JTable
            DefaultTableModel model = (DefaultTableModel) tbPhieuQuaHan.getModel();
            int rowCount = model.getRowCount();
            int columnCount = model.getColumnCount();
            // Lấy dữ liệu từ JTextField
            String textField1Value = lbTongSach.getText();
          String textField2Value = lbTongKhach.getText();
          String textField3Value = lbTongPhieu.getText();
          String textField4Value = lbTongPhieuQuaHan.getText();
            
            // Thêm dữ liệu từ JTextField vào nội dung
            content.append(textField1Value).append("\n");
            content.append(textField2Value).append("\n");
            content.append(textField3Value).append("\n");
            content.append(textField4Value).append("\n");
            
            // Lặp qua từng hàng và cột trong JTable để lấy dữ liệu
            for (int row = 0; row < rowCount; row++) {
                for (int col = 0; col < columnCount; col++) {
                    Object cellValue = model.getValueAt(row, col);
                    content.append(cellValue).append("\t"); // Sử dụng ký tự tab ("\t") để phân tách các giá trị
                }
                content.append("\n"); // Sử dụng ký tự xuống dòng ("\n") để phân tách các hàng
            }
            
            
            // Ghi nội dung vào tệp tin đã chọn
            jfc.setDialogTitle("Save File");
            FileOutputStream fos = new FileOutputStream(jfc.getSelectedFile());
            fos.write(content.toString().getBytes());
            fos.flush();
            fos.close();
            
            JOptionPane.showMessageDialog(null, "Lưu thành công");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTongKhach;
    private javax.swing.JLabel lbTongPhieu;
    private javax.swing.JLabel lbTongPhieuQuaHan;
    private javax.swing.JLabel lbTongSach;
    private javax.swing.JTable tbPhieuQuaHan;
    // End of variables declaration//GEN-END:variables
}
